pipelines:
  - name: pipeline_u20langTests
    steps:
      - name: sample_u20
        type: Bash
        execution:
          onExecute:
            - echo "Hello testing all u20"
            
      - name: u20cpp8_0_1
        type: Bash
        configuration:
          inputSteps:
            - name: sample_u20
          runtime:
            type: image
            image:
              auto:
                language: cpp
                versions:
                  - "8.0.1"

        execution:
          onExecute:
            - clang --version
            - gcc --version     
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #             - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
#             - terraform --version
            #- |
            #  [[ "$(clang --version)" == *"$step_iamge_tag"* ]]
              
      - name: u20cpp9_0_1
        type: Bash
        configuration:
          inputSteps:
            - name: sample_u20        
          runtime:
            type: image
            image:
              auto:
                language: cpp
                versions:
                  - 9.0.1
        execution:
          onExecute:
            - clang --version
            - gcc --version     
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #             - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version 
#             - terraform --version
            
           # - |
           #   [[ "$(clang --version)" == *"9.0.0"* ]]
           
      - name: u20cpp10_0_0
        type: Bash
        configuration:
          inputSteps:
            - name: sample_u20        
          runtime:
            type: image
            image:
              auto:
                language: cpp
                versions:
                  - 10.0.0
        execution:
          onExecute:
            - clang --version
            - gcc --version     
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #             - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version 
#             - terraform --version
            
           # - |
           #   [[ "$(clang --version)" == *"9.0.0"* ]]

      - name: u20go1_15_2
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              auto:
                language: go
                versions: 
                  - 1.15.2
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:   
            - source /root/.gvm/scripts/gvm
            - gvm list
            - gvm use 1.15
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #            - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
           # - |
           #   [[ "$(go version)" == *"$step_image_tag"* ]]

      - name: u20go1_14_4
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              auto:
                language: go
                versions: 
                  - 1.14.4
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:   
            - source /root/.gvm/scripts/gvm
            - gvm list
            - gvm use 1.14
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #            - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
           # - |
           #   [[ "$(go version)" == *"$step_image_tag"* ]]

      - name: u20go1_13_12
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              auto:
                language: go
                versions: 
                  - 1.13.12
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:   
            - source /root/.gvm/scripts/gvm
            - gvm list
            - gvm use 1.13
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #            - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
           # - |
           #   [[ "$(go version)" == *"$step_image_tag"* ]]

      - name: u20go1_12_17
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              auto:
                language: go
                versions: 
                  - 1.12.17
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:   
            - source /root/.gvm/scripts/gvm
            - gvm list
            - gvm use 1.12
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #            - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
           # - |
           #   [[ "$(go version)" == *"$step_image_tag"* ]]
              
              
      - name: u20go1_11_13
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              auto:
                language: go
                versions: 
                  - 1.11.13
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:   
            - source /root/.gvm/scripts/gvm
            - gvm list
            - gvm use 1.11
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #            - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
           # - |
           #   [[ "$(go version)" == *"$step_image_tag"* ]]
 
       - name: u20java15
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "15"
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:
            - java --version
            - ant -version
            - mvn --version
            - gradle --version
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #            - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - helm version --client
#             - ansible --version
#             - packer --version
#             - terraform --version
           # - |
            #  [[ "$(java --version)" == *"$step_iamge_tag"* ]] 
 
      - name: u20java11
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:
            - java --version
            - ant -version
            - mvn --version
#             - gradle --version
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #            - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - helm version --client
#             - ansible --version
#             - packer --version
#             - terraform --version
           # - |
            #  [[ "$(java --version)" == *"$step_iamge_tag"* ]] 
              
      - name: u20java8
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "8"
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:
            - java -version
            - ant -version
            - mvn --version
            - gradle --version
#             - var=$(java -version 2>&1 >/dev/null |  awk '{print $3}' | head -1)
#             - java -version
#             - ant -version
#             - gradle --version
#             - mvn --version
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #             - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
           # - |
           #   [[ $var == *"1.8.0_222"* ]]
              
      - name: u20node10_21_0
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "10.21.0"
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:
            - node --version
            - npm --version
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #             - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
           # - |
           #   [[ "$(node --version)" == *"10.16.3"* ]] 
      
      - name: u20node12_18_2
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "12.18.2"
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:
            - node --version
            - npm --version
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #             - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
#            # - |
#            #   [[ "$(node --version)" == *"12.14.0"* ]]
           
      - name: u20node8_17_0
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "8.17.0"
          inputSteps:
            - name: sample_u20
        execution:
          onExecute:
            - node --version
            - npm --version
#             - aws --version
#             - git --version
#             - pip --version
#             - virtualenv --version
# #             - eb --version
#             - az --version
#             - jfrog --version
#             - gcloud version
#             - kubectl version --client
#             - terraform --version
#             - helm version --client
#             - ansible --version
#             - packer --version
#            # - |
#            #   [[ "$(node -v)" == *"8.16.0"* ]]
