pipelines:
  - name: pipeline_c7langTests
    steps:
      - name: sample_c7
        type: Bash
        execution:
          onExecute:
            - echo "Hello testing all c7"
            
      - name: c7cpp8_3_1
        type: Bash
        configuration:
          inputSteps:
            - name: sample_c7
          runtime:
            type: image
            image:
              auto:
                language: cpp
                versions:
                  - "8.3.1"

        execution:
          onExecute:
            - clang --version
            - gcc --version     
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#             - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - terraform --version
            - helm version --client
            - ansible --version
            - packer --version
            - terraform --version
            #- |
            #  [[ "$(clang --version)" == *"$step_iamge_tag"* ]]
              
      - name: c7cpp7_0_1
        type: Bash
        configuration:
          inputSteps:
            - name: sample_c7        
          runtime:
            type: image
            image:
              auto:
                language: cpp
                versions:
                  - 7.0.1
        execution:
          onExecute:
            - clang --version
            - gcc --version     
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#             - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - terraform --version
            - helm version --client
            - ansible --version
            - packer --version 
            - terraform --version
            
           # - |
           #   [[ "$(clang --version)" == *"9.0.0"* ]]

      - name: c7go1_13_5
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              auto:
                language: go
                versions: 
                  - 1.13.5
          inputSteps:
            - name: sample_c7
        execution:
          onExecute:   
            - source /root/.gvm/scripts/gvm
            - gvm list
            - gvm use 1.13
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#            - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - terraform --version
            - helm version --client
            - ansible --version
            - packer --version
           # - |
           #   [[ "$(go version)" == *"$step_image_tag"* ]]

      - name: c7go1_12_14
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              auto:
                language: go
                versions: 
                  - 1.12.14
          inputSteps:
            - name: sample_c7
        execution:
          onExecute:   
            - source /root/.gvm/scripts/gvm
            - gvm list
            - gvm use 1.12
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#            - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - terraform --version
            - helm version --client
            - ansible --version
            - packer --version
           # - |
           #   [[ "$(go version)" == *"$step_image_tag"* ]]
              
              
      - name: c7go1_11_13
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              auto:
                language: go
                versions: 
                  - 1.11.13
          inputSteps:
            - name: sample_c7
        execution:
          onExecute:   
            - source /root/.gvm/scripts/gvm
            - gvm list
            - gvm use 1.11
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#            - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - terraform --version
            - helm version --client
            - ansible --version
            - packer --version
           # - |
           #   [[ "$(go version)" == *"$step_image_tag"* ]]
              
      - name: c7java11
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
          inputSteps:
            - name: sample_c7
        execution:
          onExecute:
            - java --version
            - ant -version
            - mvn --version
            - gradle --version
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#            - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - helm version --client
            - ansible --version
            - packer --version
            - terraform --version
           # - |
            #  [[ "$(java --version)" == *"$step_iamge_tag"* ]] 
              
      - name: c7java8
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "8"
          inputSteps:
            - name: sample_c7
        execution:
          onExecute:
            - java -version
            - ant -version
            - mvn --version
            - gradle --version
            - var=$(java -version 2>&1 >/dev/null |  awk '{print $3}' | head -1)
            - java -version
            - ant -version
            - gradle --version
            - mvn --version
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#             - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - terraform --version
            - helm version --client
            - ansible --version
            - packer --version
           # - |
           #   [[ $var == *"1.8.0_222"* ]]
              
      - name: c7node10_18_0
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "10.18.0"
          inputSteps:
            - name: sample_c7
        execution:
          onExecute:
            - node --version
            - npm --version
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#             - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - terraform --version
            - helm version --client
            - ansible --version
            - packer --version
           # - |
           #   [[ "$(node --version)" == *"10.16.3"* ]] 
      
      - name: c7node12_14_0
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "12.14.0"
          inputSteps:
            - name: sample_c7
        execution:
          onExecute:
            - node --version
            - npm --version
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#             - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - terraform --version
            - helm version --client
            - ansible --version
            - packer --version
           # - |
           #   [[ "$(node --version)" == *"12.14.0"* ]]
           
      - name: c7node8_17_0
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "8.17.0"
          inputSteps:
            - name: sample_c7
        execution:
          onExecute:
            - node --version
            - npm --version
            - aws --version
            - git --version
            - pip --version
            - virtualenv --version
#             - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - kubectl version --client
            - terraform --version
            - helm version --client
            - ansible --version
            - packer --version
           # - |
           #   [[ "$(node -v)" == *"8.16.0"* ]]
